# Numpy Crash Course

written by Mehdi Paydayesh, 27/04/2019

NumPy (stands for Numerical Python) is one of the most powerful and widely used Python libraries for Data Scientists and Machine Learning engineers. Understanding NumPy is the starting point of data processing and later implementing ML Algorithms. It provides high-performance multidimensional array objects (especially when compared with Python lists!), and functions for working with these arrays. The main application in data science is performing linear algebra, Fourier transform, and random number capabilities

I have put together a Notebook in my GitHub repository that covers the basics of NumPy array manipulation to access data and subarrays, and to split, reshape and generate random numbers. While the types of operations may seem a bit dry, they comprise the building blocks of many other examples used in Python programming in Machine Learning. 
My Jupiter notebook contains a crash course of NumPy that provides the common NumPy operations in an easy-to-follow style. Hope you enjoy it!

The notebook file includes the following sections:

**Part 0: importing libararies**

**Part 1: bulitin functions in numpy**

**Part 2: max, min and mean operations**

**Part 3: reshaping**

**Part 4: indexing**

**Part 5: masking**


## importing libararies

In [1]:
import numpy as np

In [2]:
mylist=[1,2,3,4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
mylist

[1, 2, 3, 4]

In [5]:
type(mylist)

list

In [8]:
# changing the type of variable
arr=np.array(mylist)
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4])

## bulitin functions in numpy

In [14]:
a=np.arange(0,10)
# a=np.arange(0,10,2) # with step size
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# creating an array of zeros
np.zeros ((10,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# creating an array of ones
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# a note on floating and intiger types 
a=type(1.0) 
b=type(1.)
c=type (1)
print (a,b,c)

<class 'float'> <class 'float'> <class 'int'>


In [22]:
# creating a random intiger; the following command returns a random number between the lower and upper limits
np.random.randint(0,100)

49

In [26]:
# creating ad random array of intigers
np.random.randint(0,100,(5,4))

array([[28, 43, 68, 46],
       [53, 32, 42, 47],
       [32, 60, 91, 98],
       [98, 71, 18, 70],
       [ 8,  4, 40, 60]])

In [28]:
# creating a linearly spcaed array
np.linspace(0,10,6) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [30]:
# getting teh same random number by using seed number
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

## max, min and mean operations

In [57]:
# max, min and mean operations
arr=np.random.randint(0,100,10)
a=arr.max()
b=arr.min()
c=arr.mean()

# locations of min and max
d=arr.argmax()
e=arr.argmin()
print (arr)
print (a)
print (b)
print (c)
print (d)
print (e)

[ 2 18 58 92 11 10 94 35 28  3]
94
2
35.1
6
0


## reshaping

In [ ]:
# reshaping an array
arr.reshape(2,5)

## indexing

In [47]:
# indexing
mat=np.arange(0,100).reshape(10,10) # creating a two-dimentional array or matrix
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
# selecting an individual number of the 'mat' array
#lets grab '52'
a=mat[5,2]
# lets grab the third column
b=mat[:,2]
# lets grab the second row
c=mat[1,:]
print(a)
print(b)
print(c)

52
[ 2 12 22 32 42 52 62 72 82 92]
[10 11 12 13 14 15 16 17 18 19]


## masking
masking allows you to use conditioning filter to grab elements 

In [59]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [60]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])